<!DOCTYPE html>
<html><head><title>GetIncidentRootCausesAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">4 references to GetIncidentRootCausesAsync</div><div class="rA">Azure.AI.MetricsAdvisor.Tests (4)</div><div class="rG" id="Azure.AI.MetricsAdvisor.Tests"><div class="rF"><div class="rN">MetricsAdvisorClient\AnomalyDetectionLiveTests.cs (2)</div>
<a href="../../Azure.AI.MetricsAdvisor.Tests/MetricsAdvisorClient/AnomalyDetectionLiveTests.cs.html#245"><b>245</b>await foreach (IncidentRootCause rootCause in client.<i>GetIncidentRootCausesAsync</i>(incident))</a>
<a href="../../Azure.AI.MetricsAdvisor.Tests/MetricsAdvisorClient/AnomalyDetectionLiveTests.cs.html#280"><b>280</b>await foreach (IncidentRootCause rootCause in client.<i>GetIncidentRootCausesAsync</i>(incident))</a>
</div>
<div class="rF"><div class="rN">MetricsAdvisorClient\AnomalyDetectionTests.cs (2)</div>
<a href="../../Azure.AI.MetricsAdvisor.Tests/MetricsAdvisorClient/AnomalyDetectionTests.cs.html#131"><b>131</b>Assert.That(() =&gt; client.<i>GetIncidentRootCausesAsync</i>(null), Throws.InstanceOf&lt;ArgumentNullException&gt;());</a>
<a href="../../Azure.AI.MetricsAdvisor.Tests/MetricsAdvisorClient/AnomalyDetectionTests.cs.html#149"><b>149</b>IAsyncEnumerator&lt;IncidentRootCause&gt; asyncEnumerator = client.<i>GetIncidentRootCausesAsync</i>(incident, cancellationSource.Token).GetAsyncEnumerator();</a>
</div>
</div>
</body></html>