<!DOCTYPE html>
<html><head><title>ErrorResponseException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">2 instantiations of ErrorResponseException</div><div class="rA">Microsoft.Azure.Management.ResourceGraph (2)</div><div class="rG" id="Microsoft.Azure.Management.ResourceGraph"><div class="rF"><div class="rN">Generated\Operations.cs (1)</div>
<a href="../Generated/Operations.cs.html#161"><b>161</b>var ex = new <i>ErrorResponseException</i>(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
<div class="rF"><div class="rN">Generated\ResourceGraphClient.cs (1)</div>
<a href="../Generated/ResourceGraphClient.cs.html#484"><b>484</b>var ex = new <i>ErrorResponseException</i>(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
</div>
<div class="rH">7 references to ErrorResponseException</div><div class="rA">Microsoft.Azure.Management.ResourceGraph (5)</div><div class="rG" id="Microsoft.Azure.Management.ResourceGraph"><div class="rF"><div class="rN">Generated\IOperations.cs (1)</div>
<a href="../Generated/IOperations.cs.html#35"><b>35</b>/// &lt;exception cref=&quot;<i>ErrorResponseException</i>&quot;&gt;</a>
</div>
<div class="rF"><div class="rN">Generated\Operations.cs (2)</div>
<a href="../Generated/Operations.cs.html#62"><b>62</b>/// &lt;exception cref=&quot;<i>ErrorResponseException</i>&quot;&gt;</a>
<a href="../Generated/Operations.cs.html#161"><b>161</b><i>var</i> ex = new ErrorResponseException(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
<div class="rF"><div class="rN">Generated\ResourceGraphClient.cs (2)</div>
<a href="../Generated/ResourceGraphClient.cs.html#370"><b>370</b>/// &lt;exception cref=&quot;<i>ErrorResponseException</i>&quot;&gt;</a>
<a href="../Generated/ResourceGraphClient.cs.html#484"><b>484</b><i>var</i> ex = new ErrorResponseException(string.Format(&quot;Operation returned an invalid status code &#39;{0}&#39;&quot;, _statusCode));</a>
</div>
</div>
<div class="rA">Microsoft.Azure.Management.ResourceGraph.Tests (2)</div><div class="rG" id="Microsoft.Azure.Management.ResourceGraph.Tests"><div class="rF"><div class="rN">ResourceGraphTests.cs (2)</div>
<a href="../../Microsoft.Azure.Management.ResourceGraph.Tests/ResourceGraphTests.cs.html#263"><b>263</b><i>var</i> exception =</a>
<a href="../../Microsoft.Azure.Management.ResourceGraph.Tests/ResourceGraphTests.cs.html#264"><b>264</b>Assert.Throws&lt;<i>ErrorResponseException</i>&gt;(</a>
</div>
</div>
</body></html>