<!DOCTYPE html>
<html><head><title>InvokeOnProcessingEventBatchAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">6 references to InvokeOnProcessingEventBatchAsync</div><div class="rA">Azure.Messaging.EventHubs.Processor.Tests (6)</div><div class="rG" id="Azure.Messaging.EventHubs.Processor.Tests"><div class="rF"><div class="rN">Processor\EventProcessorClientTests.cs (6)</div>
<a href="../Processor/EventProcessorClientTests.cs.html#935"><b>935</b>await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(eventBatch, new TestEventProcessorPartition(partitionId), cancellationSource.Token);</a>
<a href="../Processor/EventProcessorClientTests.cs.html#982"><b>982</b>await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(Enumerable.Empty&lt;EventData&gt;(), new TestEventProcessorPartition(partitionId), cancellationSource.Token);</a>
<a href="../Processor/EventProcessorClientTests.cs.html#1033"><b>1033</b>Assert.That(async () =&gt; await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(eventBatch, new TestEventProcessorPartition(&quot;0&quot;), cancellationSource.Token), Throws.Exception.EqualTo(expectedException), &quot;The processing should have surfaced the exception&quot;);</a>
<a href="../Processor/EventProcessorClientTests.cs.html#1076"><b>1076</b>await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(eventBatch, new TestEventProcessorPartition(&quot;0&quot;), cancellationSource.Token);</a>
<a href="../Processor/EventProcessorClientTests.cs.html#1115"><b>1115</b>await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(eventBatch, new TestEventProcessorPartition(partitionId), cancellationSource.Token);</a>
<a href="../Processor/EventProcessorClientTests.cs.html#1160"><b>1160</b>await processorClient.<i>InvokeOnProcessingEventBatchAsync</i>(eventBatch, new TestEventProcessorPartition(partitionId), cancellationSource.Token).IgnoreExceptions();</a>
</div>
</div>
</body></html>