<!DOCTYPE html>
<html><head><title>InvokeDownloadToAsync</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">6 references to InvokeDownloadToAsync</div><div class="rA">Azure.Storage.Blobs.Tests (6)</div><div class="rG" id="Azure.Storage.Blobs.Tests"><div class="rF"><div class="rN">PartitionedDownloaderTests.cs (6)</div>
<a href="../PartitionedDownloaderTests.cs.html#49"><b>49</b>Response result = await <i>InvokeDownloadToAsync</i>(downloader, stream);</a>
<a href="../PartitionedDownloaderTests.cs.html#67"><b>67</b>Response result = await <i>InvokeDownloadToAsync</i>(downloader, stream);</a>
<a href="../PartitionedDownloaderTests.cs.html#95"><b>95</b>Response result = await <i>InvokeDownloadToAsync</i>(downloader, stream);</a>
<a href="../PartitionedDownloaderTests.cs.html#124"><b>124</b>Response result = await <i>InvokeDownloadToAsync</i>(downloader, stream);</a>
<a href="../PartitionedDownloaderTests.cs.html#154"><b>154</b>Response result = await <i>InvokeDownloadToAsync</i>(downloader, stream);</a>
<a href="../PartitionedDownloaderTests.cs.html#204"><b>204</b>Exception thrown = Assert.ThrowsAsync&lt;Exception&gt;(async () =&gt; await <i>InvokeDownloadToAsync</i>(downloader, stream));</a>
</div>
</div>
</body></html>