<!DOCTYPE html>
<html><head><title>IntentionalException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">5 instantiations of IntentionalException</div><div class="rA">DataLakeStore.Tests (5)</div><div class="rG" id="DataLakeStore.Tests"><div class="rF"><div class="rN">DataTransferTests\DataLakeStoreClientTests.cs (5)</div>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#334"><b>334</b>frontEnd1.ConcatenateImplementation = (target, inputs, isDownload) =&gt; { throw new <i>IntentionalException</i>(); }; //fail the concatenation</a>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#365"><b>365</b>frontEnd3.ConcatenateImplementation = (target, inputs, isDownload) =&gt; { throw new <i>IntentionalException</i>(); }; //fail the concatenation</a>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#405"><b>405</b>throw new <i>IntentionalException</i>();</a>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#450"><b>450</b>throw new <i>IntentionalException</i>();</a>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#487"><b>487</b>throw new <i>IntentionalException</i>();</a>
</div>
</div>
<div class="rH">2 references to IntentionalException</div><div class="rA">DataLakeStore.Tests (2)</div><div class="rG" id="DataLakeStore.Tests"><div class="rF"><div class="rN">DataTransferTests\DataLakeStoreClientTests.cs (2)</div>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#342"><b>342</b>Assert.Throws&lt;<i>IntentionalException</i>&gt;(() =&gt; uploader.Execute());</a>
<a href="../DataTransferTests/DataLakeStoreClientTests.cs.html#369"><b>369</b>Assert.Throws&lt;<i>IntentionalException</i>&gt;(() =&gt; uploader.Execute());</a>
</div>
</div>
</body></html>