<!DOCTYPE html>
<html><head><title>ClientDiagnostics</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">7 references to ClientDiagnostics</div><div class="rA">Azure.Core.Tests (7)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">FailedResponseExceptionTests.cs (7)</div>
<a href="../FailedResponseExceptionTests.cs.html#35"><b>35</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#54"><b>54</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#77"><b>77</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#95"><b>95</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response);</a>
<a href="../FailedResponseExceptionTests.cs.html#115"><b>115</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, errorCode: &quot;CUSTOM CODE&quot;);</a>
<a href="../FailedResponseExceptionTests.cs.html#138"><b>138</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, additionalInfo: new Dictionary&lt;string, string&gt;()</a>
<a href="../FailedResponseExceptionTests.cs.html#165"><b>165</b>RequestFailedException exception = await <i>ClientDiagnostics</i>.CreateRequestFailedExceptionAsync(response, innerException: innerException);</a>
</div>
</div>
</body></html>