<!DOCTYPE html>
<html><head><title>AdalException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 references to AdalException</div><div class="rA">Microsoft.Azure.Services.AppAuthentication.Unit.Tests (3)</div><div class="rG" id="Microsoft.Azure.Services.AppAuthentication.Unit.Tests"><div class="rF"><div class="rN">ClientSecretAccessTokenProviderTests.cs (1)</div>
<a href="../../Microsoft.Azure.Services.AppAuthentication.Unit.Tests/ClientSecretAccessTokenProviderTests.cs.html#61"><b>61</b>Assert.Contains(Constants.<i>AdalException</i>, exception.Message);</a>
</div>
<div class="rF"><div class="rN">Mocks\MockAuthenticationContext.cs (1)</div>
<a href="../../Microsoft.Azure.Services.AppAuthentication.Unit.Tests/Mocks/MockAuthenticationContext.cs.html#61"><b>61</b>throw new Exception(Constants.<i>AdalException</i>);</a>
</div>
<div class="rF"><div class="rN">WindowsAuthenticationAccessTokenProviderTests.cs (1)</div>
<a href="../../Microsoft.Azure.Services.AppAuthentication.Unit.Tests/WindowsAuthenticationAccessTokenProviderTests.cs.html#80"><b>80</b>Assert.Contains(Constants.<i>AdalException</i>, exception.Message);</a>
</div>
</div>
</body></html>