<!DOCTYPE html>
<html><head><title>AuthenticationException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">8 instantiations of AuthenticationException</div><div class="rA">Az.Auth.FullDesktop.Tests (1)</div><div class="rG" id="Az.Auth.FullDesktop.Tests"><div class="rF"><div class="rN">ExceptionsTests.cs (1)</div>
<a href="../../Az.Auth.FullDesktop.Tests/ExceptionsTests.cs.html#54"><b>54</b>authExToBeThrown = new <i>AuthenticationException</i>(authError);</a>
</div>
</div>
<div class="rA">Microsoft.Rest.ClientRuntime.Azure.Authentication (7)</div><div class="rG" id="Microsoft.Rest.ClientRuntime.Azure.Authentication"><div class="rF"><div class="rN">ApplicationTokenProvider.cs (1)</div>
<a href="../ApplicationTokenProvider.cs.html#633"><b>633</b>throw new <i>AuthenticationException</i>(Resources.ErrorAcquiringToken, authenticationException);</a>
</div>
<div class="rF"><div class="rN">MemoryApplicationAuthenticationProvider.cs (1)</div>
<a href="../MemoryApplicationAuthenticationProvider.cs.html#63"><b>63</b>throw new <i>AuthenticationException</i>(&quot;Matching credentials for client id &#39;{0}&#39; could not be found.&quot;);</a>
</div>
<div class="rF"><div class="rN">UserLoginProvider.cs (3)</div>
<a href="../UserLoginProvider.cs.html#280"><b>280</b>throw new <i>AuthenticationException</i>(</a>
<a href="../UserLoginProvider.cs.html#370"><b>370</b>throw new <i>AuthenticationException</i>(Resources.ErrorAcquiringToken, ex);</a>
<a href="../UserLoginProvider.cs.html#374"><b>374</b>throw new <i>AuthenticationException</i>(Resources.ErrorAcquiringToken, ex);</a>
</div>
<div class="rF"><div class="rN">UserTokenProvider.cs (2)</div>
<a href="../UserTokenProvider.cs.html#268"><b>268</b>throw new <i>AuthenticationException</i>(Resources.ErrorAcquiringToken, ex);</a>
<a href="../UserTokenProvider.cs.html#303"><b>303</b>throw new <i>AuthenticationException</i>(Resources.ErrorRenewingToken, authenticationException);</a>
</div>
</div>
<div class="rH">3 references to AuthenticationException</div><div class="rA">Az.Auth.FullDesktop.Tests (2)</div><div class="rG" id="Az.Auth.FullDesktop.Tests"><div class="rF"><div class="rN">ExceptionsTests.cs (2)</div>
<a href="../../Az.Auth.FullDesktop.Tests/ExceptionsTests.cs.html#20"><b>20</b><i>AuthenticationException</i> authExToBeThrown = null;</a>
<a href="../../Az.Auth.FullDesktop.Tests/ExceptionsTests.cs.html#38"><b>38</b><i>AuthenticationException</i> authExToBeThrown = null;</a>
</div>
</div>
<div class="rA">Az.Auth.Net452.Tests (1)</div><div class="rG" id="Az.Auth.Net452.Tests"><div class="rF"><div class="rN">Net452ExceptionsTests.cs (1)</div>
<a href="../../Az.Auth.Net452.Tests/Net452ExceptionsTests.cs.html#20"><b>20</b><i>AuthenticationException</i> authExToBeThrown = null;</a>
</div>
</div>
</body></html>