<!DOCTYPE html>
<html><head><title>Exception</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">1 write to Exception</div><div class="rA">Azure.Messaging.EventHubs (1)</div><div class="rG" id="Azure.Messaging.EventHubs"><div class="rF"><div class="rN">Processor\ProcessErrorEventArgs.cs (1)</div>
<a href="../Processor/ProcessErrorEventArgs.cs.html#69"><b>69</b><i>Exception</i> = exception;</a>
</div>
</div>
<div class="rH">11 references to Exception</div><div class="rA">Azure.Messaging.EventHubs.Processor.Perf (1)</div><div class="rG" id="Azure.Messaging.EventHubs.Processor.Perf"><div class="rF"><div class="rN">Scenarios\ProcessEventTest.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Perf/Scenarios/ProcessEventTest.cs.html#87"><b>87</b>ErrorRaised(arg.<i>Exception</i>);</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventHubs.Processor.Tests (10)</div><div class="rG" id="Azure.Messaging.EventHubs.Processor.Tests"><div class="rF"><div class="rN">Processor\EventProcessorClientLiveTests.cs (2)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientLiveTests.cs.html#1052"><b>1052</b>Assert.Fail($&quot;Processor Error Surfaced: ({ args.<i>Exception</i>.GetType().Name })[{ args.<i>Exception</i>.Message }]&quot;);</a>
</div>
<div class="rF"><div class="rN">Processor\EventProcessorClientTests.cs (2)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientTests.cs.html#821"><b>821</b>Assert.That(capturedEventArgs.<i>Exception</i>, Is.InstanceOf&lt;DivideByZeroException&gt;().And.Message.EqualTo(exception.Message), &quot;The exception should have been propagated.&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Processor/EventProcessorClientTests.cs.html#854"><b>854</b>Assert.That(capturedEventArgs.<i>Exception</i>, Is.InstanceOf&lt;DivideByZeroException&gt;().And.Message.EqualTo(exception.Message), &quot;The exception should have been propagated.&quot;);</a>
</div>
<div class="rF"><div class="rN">Snippets\ReadMeSnippetsLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/ReadMeSnippetsLiveTests.cs.html#106"><b>106</b>await DoSomethingWithTheError(eventArgs.<i>Exception</i>);</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample01_HelloWorldLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample01_HelloWorldLiveTests.cs.html#205"><b>205</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample03_EventProcessorHandlersLiveTests.cs (3)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#319"><b>319</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#415"><b>415</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample03_EventProcessorHandlersLiveTests.cs.html#429"><b>429</b>if (args.<i>Exception</i> is OutOfMemoryException)</a>
</div>
<div class="rF"><div class="rN">Snippets\Sample04_ProcessingEventsLiveTests.cs (1)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Snippets/Sample04_ProcessingEventsLiveTests.cs.html#97"><b>97</b>Debug.WriteLine($&quot;\tException: { args.<i>Exception</i> }&quot;);</a>
</div>
</div>
</body></html>