<!DOCTYPE html>
<html><head><title>DeveloperCodeException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">4 instantiations of DeveloperCodeException</div><div class="rA">Azure.Messaging.EventHubs (1)</div><div class="rG" id="Azure.Messaging.EventHubs"><div class="rF"><div class="rN">Primitives\EventProcessor.cs (1)</div>
<a href="../Primitives/EventProcessor.cs.html#575"><b>575</b>throw new <i>DeveloperCodeException</i>(ex);</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventHubs.Tests (3)</div><div class="rG" id="Azure.Messaging.EventHubs.Tests"><div class="rF"><div class="rN">Primitives\EventProcessorTests.PartitionProcessing.cs (3)</div>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#825"><b>825</b>var expectedException = new <i>DeveloperCodeException</i>(new DivideByZeroException());</a>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#883"><b>883</b>var expectedException = new <i>DeveloperCodeException</i>(new DivideByZeroException(&quot;Yay, I&#39;m on the inside!&quot;));</a>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#946"><b>946</b>var developerException = new <i>DeveloperCodeException</i>(expectedException);</a>
</div>
</div>
<div class="rH">7 references to DeveloperCodeException</div><div class="rA">Azure.Messaging.EventHubs (3)</div><div class="rG" id="Azure.Messaging.EventHubs"><div class="rF"><div class="rN">Core\DeveloperCodeException.cs (1)</div>
<a href="../Core/DeveloperCodeException.cs.html#21"><b>21</b>///   Initializes a new instance of the &lt;see cref=&quot;<i>DeveloperCodeException</i>&quot;/&gt; class.</a>
</div>
<div class="rF"><div class="rN">Primitives\EventProcessor.cs (2)</div>
<a href="../Primitives/EventProcessor.cs.html#697"><b>697</b>catch (Exception ex) when (ex.IsNotType&lt;<i>DeveloperCodeException</i>&gt;())</a>
<a href="../Primitives/EventProcessor.cs.html#723"><b>723</b>catch (<i>DeveloperCodeException</i> ex)</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventHubs.Tests (4)</div><div class="rG" id="Azure.Messaging.EventHubs.Tests"><div class="rF"><div class="rN">Primitives\EventProcessorTests.PartitionProcessing.cs (4)</div>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#130"><b>130</b>Assert.That(async () =&gt; await mockProcessor.Object.ProcessEventBatchAsync(partition, EmptyBatch, true, cancellationSource.Token), Throws.InstanceOf&lt;<i>DeveloperCodeException</i>&gt;().And.Message.EqualTo(Resources.DeveloperCodeError));</a>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#825"><b>825</b><i>var</i> expectedException = new DeveloperCodeException(new DivideByZeroException());</a>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#883"><b>883</b><i>var</i> expectedException = new DeveloperCodeException(new DivideByZeroException(&quot;Yay, I&#39;m on the inside!&quot;));</a>
<a href="../../Azure.Messaging.EventHubs.Tests/Primitives/EventProcessorTests.PartitionProcessing.cs.html#946"><b>946</b><i>var</i> developerException = new DeveloperCodeException(expectedException);</a>
</div>
</div>
</body></html>