<!DOCTYPE html>
<html><head><title>RequestFailedException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">98 references to RequestFailedException</div><div class="rA">Azure.AI.AnomalyDetector (1)</div><div class="rG" id="Azure.AI.AnomalyDetector"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.AnomalyDetector/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.FormRecognizer (1)</div><div class="rG" id="Azure.AI.FormRecognizer"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.FormRecognizer/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.Language.QuestionAnswering (1)</div><div class="rG" id="Azure.AI.Language.QuestionAnswering"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.Language.QuestionAnswering/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.MetricsAdvisor (1)</div><div class="rG" id="Azure.AI.MetricsAdvisor"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.MetricsAdvisor/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.Personalizer (1)</div><div class="rG" id="Azure.AI.Personalizer"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.Personalizer/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.TextAnalytics (1)</div><div class="rG" id="Azure.AI.TextAnalytics"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.TextAnalytics/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.AI.Translation.Document (1)</div><div class="rG" id="Azure.AI.Translation.Document"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.AI.Translation.Document/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Purview.Account (1)</div><div class="rG" id="Azure.Analytics.Purview.Account"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Purview.Account/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Purview.Catalog (1)</div><div class="rG" id="Azure.Analytics.Purview.Catalog"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Purview.Catalog/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Purview.Scanning (1)</div><div class="rG" id="Azure.Analytics.Purview.Scanning"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Purview.Scanning/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Synapse.AccessControl (1)</div><div class="rG" id="Azure.Analytics.Synapse.AccessControl"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Synapse.AccessControl/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Synapse.Artifacts (1)</div><div class="rG" id="Azure.Analytics.Synapse.Artifacts"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Synapse.Artifacts/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Synapse.ManagedPrivateEndpoints (1)</div><div class="rG" id="Azure.Analytics.Synapse.ManagedPrivateEndpoints"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Synapse.ManagedPrivateEndpoints/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Synapse.Monitoring (1)</div><div class="rG" id="Azure.Analytics.Synapse.Monitoring"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Synapse.Monitoring/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Analytics.Synapse.Spark (1)</div><div class="rG" id="Azure.Analytics.Synapse.Spark"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Analytics.Synapse.Spark/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.CallingServer (1)</div><div class="rG" id="Azure.Communication.CallingServer"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.CallingServer/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.Chat (1)</div><div class="rG" id="Azure.Communication.Chat"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.Chat/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.Identity (1)</div><div class="rG" id="Azure.Communication.Identity"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.Identity/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.NetworkTraversal (1)</div><div class="rG" id="Azure.Communication.NetworkTraversal"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.NetworkTraversal/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.PhoneNumbers (1)</div><div class="rG" id="Azure.Communication.PhoneNumbers"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.PhoneNumbers/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Communication.Sms (1)</div><div class="rG" id="Azure.Communication.Sms"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Communication.Sms/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Containers.ContainerRegistry (1)</div><div class="rG" id="Azure.Containers.ContainerRegistry"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Containers.ContainerRegistry/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Core (2)</div><div class="rG" id="Azure.Core"><div class="rF"><div class="rN">RequestFailedException.cs (1)</div>
<a href="../RequestFailedException.cs.html#53"><b>53</b>: <i>this</i>(status, message, null, innerException)</a>
</div>
<div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Core.Tests (1)</div><div class="rG" id="Azure.Core.Tests"><div class="rF"><div class="rN">FailedResponseExceptionTests.cs (1)</div>
<a href="../../Azure.Core.Tests/FailedResponseExceptionTests.cs.html#174"><b>174</b>var exception = new <i>RequestFailedException</i>(201, &quot;Message&quot;, &quot;Error&quot;, null);</a>
</div>
</div>
<div class="rA">Azure.Data.AppConfiguration (1)</div><div class="rG" id="Azure.Data.AppConfiguration"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Data.AppConfiguration/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Data.SchemaRegistry (1)</div><div class="rG" id="Azure.Data.SchemaRegistry"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Data.SchemaRegistry/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Data.Tables (2)</div><div class="rG" id="Azure.Data.Tables"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Data.Tables/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
<div class="rF"><div class="rN">TableTransactionFailedException.cs (1)</div>
<a href="../../Azure.Data.Tables/TableTransactionFailedException.cs.html#27"><b>27</b>: <i>base</i>(</a>
</div>
</div>
<div class="rA">Azure.DigitalTwins.Core (1)</div><div class="rG" id="Azure.DigitalTwins.Core"><div class="rF"><div class="rN">Shared\Azure.Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.DigitalTwins.Core/Shared/Azure.Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Graph.Rbac (1)</div><div class="rG" id="Azure.Graph.Rbac"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Graph.Rbac/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Identity (1)</div><div class="rG" id="Azure.Identity"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Identity/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Identity.Perf (1)</div><div class="rG" id="Azure.Identity.Perf"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Identity.Perf/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.IoT.DeviceUpdate (1)</div><div class="rG" id="Azure.IoT.DeviceUpdate"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.IoT.DeviceUpdate/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.IoT.Hub.Service (1)</div><div class="rG" id="Azure.IoT.Hub.Service"><div class="rF"><div class="rN">Shared\Azure.Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.IoT.Hub.Service/Shared/Azure.Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.IoT.ModelsRepository (3)</div><div class="rG" id="Azure.IoT.ModelsRepository"><div class="rF"><div class="rN">Fetchers\HttpModelFetcher.cs (2)</div>
<a href="../../Azure.IoT.ModelsRepository/Fetchers/HttpModelFetcher.cs.html#124"><b>124</b>throw new <i>RequestFailedException</i>(</a>
<a href="../../Azure.IoT.ModelsRepository/Fetchers/HttpModelFetcher.cs.html#132"><b>132</b>throw new <i>RequestFailedException</i>(</a>
</div>
<div class="rF"><div class="rN">Shared\Azure.Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.IoT.ModelsRepository/Shared/Azure.Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.IoT.TimeSeriesInsights (1)</div><div class="rG" id="Azure.IoT.TimeSeriesInsights"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.IoT.TimeSeriesInsights/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Media.VideoAnalyzer.Edge (1)</div><div class="rG" id="Azure.Media.VideoAnalyzer.Edge"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Media.VideoAnalyzer.Edge/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventGrid (1)</div><div class="rG" id="Azure.Messaging.EventGrid"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Messaging.EventGrid/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventHubs.Processor.Tests (7)</div><div class="rG" id="Azure.Messaging.EventHubs.Processor.Tests"><div class="rF"><div class="rN">Diagnostics\BlobsCheckpointStoreDiagnosticsTests.cs (7)</div>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#73"><b>73</b>var ex = new <i>RequestFailedException</i>(0, &quot;foo&quot;, BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#352"><b>352</b>var ex = new <i>RequestFailedException</i>(0, &quot;foo&quot;, BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#520"><b>520</b>var ex = new <i>RequestFailedException</i>(404, BlobErrorCode.ContainerNotFound.ToString(), BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#689"><b>689</b>throw new <i>RequestFailedException</i>(404, BlobErrorCode.BlobNotFound.ToString(), BlobErrorCode.BlobNotFound.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#697"><b>697</b>throw new <i>RequestFailedException</i>(412, BlobErrorCode.ConditionNotMet.ToString(), BlobErrorCode.ConditionNotMet.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#709"><b>709</b>throw new <i>RequestFailedException</i>(409, BlobErrorCode.BlobAlreadyExists.ToString(), BlobErrorCode.BlobAlreadyExists.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Processor.Tests/Diagnostics/BlobsCheckpointStoreDiagnosticsTests.cs.html#729"><b>729</b>throw new <i>RequestFailedException</i>(404, BlobErrorCode.BlobNotFound.ToString(), BlobErrorCode.BlobNotFound.ToString(), default);</a>
</div>
</div>
<div class="rA">Azure.Messaging.EventHubs.Shared.Tests (8)</div><div class="rG" id="Azure.Messaging.EventHubs.Shared.Tests"><div class="rF"><div class="rN">BlobCheckpointStore\BlobsCheckpointStoreTests.cs (8)</div>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#113"><b>113</b>var ex = new <i>RequestFailedException</i>(0, &quot;foo&quot;, BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#747"><b>747</b>var ex = new <i>RequestFailedException</i>(0, &quot;foo&quot;, BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#916"><b>916</b>var ex = new <i>RequestFailedException</i>(404, BlobErrorCode.ContainerNotFound.ToString(), BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#1828"><b>1828</b>var ex = new <i>RequestFailedException</i>(0, &quot;foo&quot;, BlobErrorCode.ContainerNotFound.ToString(), null);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#1927"><b>1927</b>throw new <i>RequestFailedException</i>(404, BlobErrorCode.BlobNotFound.ToString(), BlobErrorCode.BlobNotFound.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#1935"><b>1935</b>throw new <i>RequestFailedException</i>(412, BlobErrorCode.ConditionNotMet.ToString(), BlobErrorCode.ConditionNotMet.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#1949"><b>1949</b>throw new <i>RequestFailedException</i>(409, BlobErrorCode.BlobAlreadyExists.ToString(), BlobErrorCode.BlobAlreadyExists.ToString(), default);</a>
<a href="../../Azure.Messaging.EventHubs.Shared.Tests/BlobCheckpointStore/BlobsCheckpointStoreTests.cs.html#1973"><b>1973</b>throw new <i>RequestFailedException</i>(404, BlobErrorCode.BlobNotFound.ToString(), BlobErrorCode.BlobNotFound.ToString(), default);</a>
</div>
</div>
<div class="rA">Azure.Messaging.ServiceBus (1)</div><div class="rG" id="Azure.Messaging.ServiceBus"><div class="rF"><div class="rN">SharedSource\Azure.Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Messaging.ServiceBus/SharedSource/Azure.Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Messaging.WebPubSub (1)</div><div class="rG" id="Azure.Messaging.WebPubSub"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Messaging.WebPubSub/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.MixedReality.Authentication (1)</div><div class="rG" id="Azure.MixedReality.Authentication"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.MixedReality.Authentication/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.MixedReality.ObjectAnchors.Conversion (1)</div><div class="rG" id="Azure.MixedReality.ObjectAnchors.Conversion"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.MixedReality.ObjectAnchors.Conversion/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.MixedReality.RemoteRendering (1)</div><div class="rG" id="Azure.MixedReality.RemoteRendering"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.MixedReality.RemoteRendering/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Monitor.OpenTelemetry.Exporter (1)</div><div class="rG" id="Azure.Monitor.OpenTelemetry.Exporter"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Monitor.OpenTelemetry.Exporter/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Monitor.Query (2)</div><div class="rG" id="Azure.Monitor.Query"><div class="rF"><div class="rN">Models\LogsBatchQueryResults.cs (1)</div>
<a href="../../Azure.Monitor.Query/Models/LogsBatchQueryResults.cs.html#58"><b>58</b>throw new <i>RequestFailedException</i>(result.Status ?? 0, message, result.Body.Error.Code, null);</a>
</div>
<div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Monitor.Query/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Quantum.Jobs (1)</div><div class="rG" id="Azure.Quantum.Jobs"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Quantum.Jobs/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager (1)</div><div class="rG" id="Azure.ResourceManager"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.AppConfiguration (1)</div><div class="rG" id="Azure.ResourceManager.AppConfiguration"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.AppConfiguration/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Communication (1)</div><div class="rG" id="Azure.ResourceManager.Communication"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Communication/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Compute (1)</div><div class="rG" id="Azure.ResourceManager.Compute"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Compute/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.CosmosDB (1)</div><div class="rG" id="Azure.ResourceManager.CosmosDB"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.CosmosDB/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Dns (1)</div><div class="rG" id="Azure.ResourceManager.Dns"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Dns/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.EventHubs (1)</div><div class="rG" id="Azure.ResourceManager.EventHubs"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.EventHubs/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Insights (1)</div><div class="rG" id="Azure.ResourceManager.Insights"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Insights/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.KeyVault (1)</div><div class="rG" id="Azure.ResourceManager.KeyVault"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.KeyVault/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.MachineLearningServices (1)</div><div class="rG" id="Azure.ResourceManager.MachineLearningServices"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.MachineLearningServices/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Network (1)</div><div class="rG" id="Azure.ResourceManager.Network"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Network/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Resources (1)</div><div class="rG" id="Azure.ResourceManager.Resources"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Resources/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Sql (1)</div><div class="rG" id="Azure.ResourceManager.Sql"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Sql/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.ResourceManager.Storage (1)</div><div class="rG" id="Azure.ResourceManager.Storage"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.ResourceManager.Storage/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Search.Documents (1)</div><div class="rG" id="Azure.Search.Documents"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Search.Documents/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.Attestation (1)</div><div class="rG" id="Azure.Security.Attestation"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.Attestation/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.ConfidentialLedger (1)</div><div class="rG" id="Azure.Security.ConfidentialLedger"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.ConfidentialLedger/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.KeyVault.Administration (1)</div><div class="rG" id="Azure.Security.KeyVault.Administration"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.KeyVault.Administration/Shared/Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.KeyVault.Certificates (1)</div><div class="rG" id="Azure.Security.KeyVault.Certificates"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.KeyVault.Certificates/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.KeyVault.Keys (1)</div><div class="rG" id="Azure.Security.KeyVault.Keys"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.KeyVault.Keys/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Security.KeyVault.Secrets (1)</div><div class="rG" id="Azure.Security.KeyVault.Secrets"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Security.KeyVault.Secrets/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Blobs (1)</div><div class="rG" id="Azure.Storage.Blobs"><div class="rF"><div class="rN">SharedCore\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Blobs/SharedCore/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Blobs.Batch (1)</div><div class="rG" id="Azure.Storage.Blobs.Batch"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Blobs.Batch/Shared/Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Blobs.ChangeFeed (1)</div><div class="rG" id="Azure.Storage.Blobs.ChangeFeed"><div class="rF"><div class="rN">Shared\Core\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Blobs.ChangeFeed/Shared/Core/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Files.DataLake (2)</div><div class="rG" id="Azure.Storage.Files.DataLake"><div class="rF"><div class="rN">ErrorExtensions.cs (1)</div>
<a href="../../Azure.Storage.Files.DataLake/ErrorExtensions.cs.html#59"><b>59</b>return new <i>RequestFailedException</i>(</a>
</div>
<div class="rF"><div class="rN">SharedCore\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Files.DataLake/SharedCore/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Files.Shares (1)</div><div class="rG" id="Azure.Storage.Files.Shares"><div class="rF"><div class="rN">SharedCore\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Files.Shares/SharedCore/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Storage.Queues (1)</div><div class="rG" id="Azure.Storage.Queues"><div class="rF"><div class="rN">SharedCore\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Storage.Queues/SharedCore/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Template (1)</div><div class="rG" id="Azure.Template"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Template/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Azure.Verticals.AgriFood.Farming (1)</div><div class="rG" id="Azure.Verticals.AgriFood.Farming"><div class="rF"><div class="rN">Shared\ClientDiagnostics.cs (1)</div>
<a href="../../Azure.Verticals.AgriFood.Farming/Shared/ClientDiagnostics.cs.html#108"><b>108</b>var exception = new <i>RequestFailedException</i>(response.Status, formatMessage, errorCode, innerException);</a>
</div>
</div>
<div class="rA">Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests (3)</div><div class="rG" id="Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests"><div class="rF"><div class="rN">QueueListenerTests.cs (3)</div>
<a href="../../Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests/QueueListenerTests.cs.html#124"><b>124</b>var exception = new <i>RequestFailedException</i>(</a>
<a href="../../Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests/QueueListenerTests.cs.html#543"><b>543</b>var exception = new <i>RequestFailedException</i>(</a>
<a href="../../Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests/QueueListenerTests.cs.html#590"><b>590</b>var exception = new <i>RequestFailedException</i>(</a>
</div>
</div>
</body></html>