<!DOCTYPE html>
<html><head><title>ProvisioningState</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">1 write to ProvisioningState</div><div class="rA">Microsoft.Azure.Management.NetApp (1)</div><div class="rG" id="Microsoft.Azure.Management.NetApp"><div class="rF"><div class="rN">Generated\Models\Backup.cs (1)</div>
<a href="../Generated/Models/Backup.cs.html#59"><b>59</b><i>ProvisioningState</i> = provisioningState;</a>
</div>
</div>
<div class="rH">5 references to ProvisioningState</div><div class="rA">NetApp.Tests (5)</div><div class="rG" id="NetApp.Tests"><div class="rF"><div class="rN">ResourceTests\BackupTests.cs (5)</div>
<a href="../../NetApp.Tests/ResourceTests/BackupTests.cs.html#194"><b>194</b>.HandleResult&lt;Backup&gt;(b =&gt; !(b.<i>ProvisioningState</i>.Equals(&quot;Succeeded&quot;) || b.<i>ProvisioningState</i>.Equals(&quot;Failed&quot;))) // retry if Provisioning state is not Succeeded</a>
<a href="../../NetApp.Tests/ResourceTests/BackupTests.cs.html#198"><b>198</b>.HandleResult&lt;Backup&gt;(b =&gt; (!b.<i>ProvisioningState</i>.Equals(&quot;Succeeded&quot;) || b.<i>ProvisioningState</i>.Equals(&quot;Failed&quot;))) // Fail the test run if Provisioning state is not Succeeded by now</a>
<a href="../../NetApp.Tests/ResourceTests/BackupTests.cs.html#202"><b>202</b>throw new Exception($&quot;Provision state {backup.<i>ProvisioningState</i>} after {count} retires waiting for backup Provisioning state to be Succeeded&quot;);</a>
</div>
</div>
</body></html>