<!DOCTYPE html>
<html><head><title>ParallelOperationsException</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">2 instantiations of ParallelOperationsException</div><div class="rA">Microsoft.Azure.Batch (1)</div><div class="rG" id="Microsoft.Azure.Batch"><div class="rF"><div class="rN">AddTasksWorkflowManager.cs (1)</div>
<a href="../AddTasksWorkflowManager.cs.html#417"><b>417</b>throw new <i>ParallelOperationsException</i>(BatchErrorMessages.MultipleParallelRequestsHitUnexpectedErrors, exceptions);</a>
</div>
</div>
<div class="rA">Microsoft.Azure.Batch.Unit.Tests (1)</div><div class="rG" id="Microsoft.Azure.Batch.Unit.Tests"><div class="rF"><div class="rN">ExceptionUnitTests.cs (1)</div>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/ExceptionUnitTests.cs.html#45"><b>45</b>ParallelOperationsException parallelOperationsException = new <i>ParallelOperationsException</i>(new Exception[] {e1, e2});</a>
</div>
</div>
<div class="rH">21 references to ParallelOperationsException</div><div class="rA">Microsoft.Azure.Batch (5)</div><div class="rG" id="Microsoft.Azure.Batch"><div class="rF"><div class="rN">BatchClientExceptions.cs (1)</div>
<a href="../BatchClientExceptions.cs.html#61"><b>61</b>/// Creates and returns a string representation of the current &lt;see cref=&quot;<i>ParallelOperationsException</i>&quot;/&gt;.</a>
</div>
<div class="rF"><div class="rN">CloudJob.cs (2)</div>
<a href="../CloudJob.cs.html#259"><b>259</b>/// &lt;exception cref=&quot;<i>ParallelOperationsException</i>&quot;&gt;Thrown if one or more requests to the Batch service fail.&lt;/exception&gt;</a>
<a href="../CloudJob.cs.html#308"><b>308</b>/// &lt;exception cref=&quot;<i>ParallelOperationsException</i>&quot;&gt;Thrown if one or more requests to the Batch service fail.&lt;/exception&gt;</a>
</div>
<div class="rF"><div class="rN">JobOperations.cs (2)</div>
<a href="../JobOperations.cs.html#1122"><b>1122</b>/// &lt;exception cref=&quot;<i>ParallelOperationsException</i>&quot;&gt;Thrown if one or more requests to the Batch service fail.&lt;/exception&gt;</a>
<a href="../JobOperations.cs.html#1175"><b>1175</b>/// &lt;exception cref=&quot;<i>ParallelOperationsException</i>&quot;&gt;Thrown if one or more requests to the Batch service fail.&lt;/exception&gt;</a>
</div>
</div>
<div class="rA">Microsoft.Azure.Batch.Integration.Tests (8)</div><div class="rG" id="Microsoft.Azure.Batch.Integration.Tests"><div class="rF"><div class="rN">AddTaskCollectionIntegrationTests.cs (8)</div>
<a href="../../Microsoft.Azure.Batch.Integration.Tests/AddTaskCollectionIntegrationTests.cs.html#134"><b>134</b><i>var</i> exception = await TestUtilities.AssertThrowsAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
<a href="../../Microsoft.Azure.Batch.Integration.Tests/AddTaskCollectionIntegrationTests.cs.html#263"><b>263</b><i>var</i> exception = await TestUtilities.AssertThrowsAsync&lt;<i>ParallelOperationsException</i>&gt;(async () =&gt;</a>
<a href="../../Microsoft.Azure.Batch.Integration.Tests/AddTaskCollectionIntegrationTests.cs.html#438"><b>438</b><i>var</i> exception = await TestUtilities.AssertThrowsAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
<a href="../../Microsoft.Azure.Batch.Integration.Tests/AddTaskCollectionIntegrationTests.cs.html#468"><b>468</b><i>var</i> exception = await TestUtilities.AssertThrowsAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
</div>
</div>
<div class="rA">Microsoft.Azure.Batch.Unit.Tests (8)</div><div class="rG" id="Microsoft.Azure.Batch.Unit.Tests"><div class="rF"><div class="rN">AddTaskCollectionUnitTests.cs (6)</div>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/AddTaskCollectionUnitTests.cs.html#59"><b>59</b><i>ParallelOperationsException</i> exception = await IssueAddTaskCollectionAndAssertExceptionIsExpectedAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/AddTaskCollectionUnitTests.cs.html#88"><b>88</b><i>ParallelOperationsException</i> exception = await IssueAddTaskCollectionAndAssertExceptionIsExpectedAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/AddTaskCollectionUnitTests.cs.html#139"><b>139</b><i>ParallelOperationsException</i> parallelOperationsException = await Assert.ThrowsAsync&lt;<i>ParallelOperationsException</i>&gt;(</a>
</div>
<div class="rF"><div class="rN">ExceptionUnitTests.cs (2)</div>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/ExceptionUnitTests.cs.html#45"><b>45</b><i>ParallelOperationsException</i> parallelOperationsException = new ParallelOperationsException(new Exception[] {e1, e2});</a>
<a href="../../Microsoft.Azure.Batch.Unit.Tests/ExceptionUnitTests.cs.html#48"><b>48</b>Assert.Contains(typeof(<i>ParallelOperationsException</i>).Name, exceptionText);</a>
</div>
</div>
</body></html>